name: maplibre_gl_platform_interface
description: A common platform interface for the maplibre_gl plugin.
version: 0.16.0
homepage: https://github.com/maplibre/flutter-maplibre-gl

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.9.1

environment:
  sdk: '>=2.15.0 <4.0.0'
  flutter: '>=2.10.0'
